"""
Context compaction for long Levy threads.

Long-thread strategy:
  1. Run normally until the running input-token total approaches the model's
     window (default 140K of 200K).
  2. Then collapse everything older than the last N turns into a single
     synthetic message — a "thread brief so far" — generated by Haiku 4.5.
  3. Also strip oversized tool_result blobs from any messages we keep, since
     a 4-round agent run can carry several KB of corpus chunks each.

What we DON'T touch:
  - The persisted transcript in `chat_messages` — Brief panel and reload still
    show the full original conversation.
  - The system prompt — it's already compact.
  - The trailing N turns — recent context matters most for coherence.

The output is the same shape Anthropic accepts (`list[dict]` of role/content
messages). The caller swaps it into the `messages=` arg before the next
`messages.create()` call.
"""

from __future__ import annotations

import json
from typing import Any

import anthropic

from ..config import get_settings


# ─── Token counting ──────────────────────────────────────────────────────────

# We don't have tiktoken for Anthropic-native tokenisation, but Claude's
# tokeniser averages ~3.5 chars/token across mixed prose + JSON tool blobs.
# This is a heuristic — we want a fast estimate to decide WHEN to compact;
# precision isn't critical because the threshold (140K) leaves 60K of slack.
_CHARS_PER_TOKEN = 3.5


def estimate_tokens(messages: list[dict]) -> int:
    """Rough token estimate for an Anthropic messages list."""
    total_chars = 0
    for m in messages:
        content = m.get("content")
        if isinstance(content, str):
            total_chars += len(content)
        elif isinstance(content, list):
            for block in content:
                if isinstance(block, dict):
                    # tool_use input + tool_result content are the heavy hitters
                    total_chars += len(json.dumps(block, default=str, ensure_ascii=False))
                else:
                    total_chars += len(str(block))
        else:
            total_chars += len(str(content))
    return int(total_chars / _CHARS_PER_TOKEN)


# ─── Per-message helpers ─────────────────────────────────────────────────────


def _truncate_tool_results_in_place(message: dict, max_chars: int) -> dict:
    """If a user message carries oversized tool_result blocks, replace each
    block's content with a short stub so the model still sees the structure
    but not the full payload. Operates on a copy."""
    content = message.get("content")
    if not isinstance(content, list):
        return message
    new_blocks = []
    truncated_any = False
    for block in content:
        if isinstance(block, dict) and block.get("type") == "tool_result":
            payload = block.get("content")
            payload_str = payload if isinstance(payload, str) else json.dumps(payload, default=str)
            if len(payload_str) > max_chars:
                head = payload_str[: max_chars - 80]
                new_blocks.append({
                    **block,
                    "content": head + f" ... [truncated by compactor — {len(payload_str)} chars]",
                })
                truncated_any = True
            else:
                new_blocks.append(block)
        else:
            new_blocks.append(block)
    if truncated_any:
        return {**message, "content": new_blocks}
    return message


def _flatten_for_summary(messages: list[dict]) -> str:
    """Turn an Anthropic messages list into plain prose for the summariser."""
    lines = []
    for m in messages:
        role = m.get("role", "?")
        content = m.get("content")
        if isinstance(content, str):
            lines.append(f"[{role}] {content}")
            continue
        if isinstance(content, list):
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")
                if btype == "text":
                    lines.append(f"[{role}] {block.get('text','')}")
                elif btype == "tool_use":
                    name = block.get("name")
                    inp = json.dumps(block.get("input") or {}, default=str)[:300]
                    lines.append(f"[{role}/tool_use] {name}({inp})")
                elif btype == "tool_result":
                    payload = block.get("content")
                    s = payload if isinstance(payload, str) else json.dumps(payload, default=str)
                    lines.append(f"[{role}/tool_result] {s[:600]}")
    return "\n".join(lines)


# ─── Public entry: compact_if_needed ─────────────────────────────────────────


_SUMMARY_SYSTEM = """You are summarising the older portion of a legal-research conversation
so the next assistant turn keeps full context without re-reading it all.

Write a tight prose brief (300-500 words) capturing:
- The user's underlying question(s) and any clarifications they've made.
- The key statutes/sections/cases that have been cited so far, with page
  numbers if mentioned. Preserve every Act + Section reference verbatim — the
  next turn will lean on these.
- Findings and gaps the assistant has surfaced (don't editorialise).
- Any artifacts that were generated (their ids and titles).
- Any decisions made about scope or direction.

Do NOT re-derive or reanalyse anything. Just compress what already happened.
Output plain prose — no markdown headings, no bullets unless absolutely
necessary."""


async def compact_if_needed(
    messages: list[dict],
    *,
    threshold_tokens: int | None = None,
    keep_last_n: int | None = None,
    old_tool_max_chars: int | None = None,
    compaction_model: str | None = None,
) -> tuple[list[dict], dict | None]:
    """
    Returns `(maybe_compacted_messages, info)`.

    `info` is `None` when no compaction was needed; otherwise it carries
    diagnostics for the caller (`{tokens_before, tokens_after, kept_messages,
    summarised_messages, summary_chars}`) so the agent can emit a `compaction`
    SSE event for the UI.
    """
    settings = get_settings()
    threshold = threshold_tokens if threshold_tokens is not None else settings.compaction_threshold_tokens
    keep = keep_last_n if keep_last_n is not None else settings.compaction_keep_last_n
    old_max = (
        old_tool_max_chars if old_tool_max_chars is not None
        else settings.compaction_old_tool_result_max_chars
    )
    model = compaction_model or settings.compaction_model

    before = estimate_tokens(messages)
    if before <= threshold:
        return messages, None

    # Need to compact. Slice off the trailing messages we keep verbatim.
    if len(messages) <= keep + 1:
        # Not enough turns to bother; just truncate big tool blobs in-place.
        return [_truncate_tool_results_in_place(m, old_max) for m in messages], None

    head = messages[:-keep]
    tail = [_truncate_tool_results_in_place(m, old_max) for m in messages[-keep:]]

    # Summarise the head with Haiku.
    flat = _flatten_for_summary(head)
    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
    try:
        resp = await client.messages.create(
            model=model,
            max_tokens=900,
            system=_SUMMARY_SYSTEM,
            messages=[{"role": "user", "content": flat}],
        )
    except anthropic.APIError as e:  # noqa: BLE001
        # Compaction failed — fall back to truncated tool results, no summary.
        truncated = [_truncate_tool_results_in_place(m, old_max) for m in messages]
        return truncated, {
            "tokens_before": before,
            "tokens_after": estimate_tokens(truncated),
            "summarised_messages": 0,
            "kept_messages": len(messages),
            "error": f"summary failed: {e}",
        }

    summary_text = ""
    for block in resp.content or []:
        if getattr(block, "type", None) == "text":
            summary_text += block.text

    # Build the compacted list: synthetic user message holding the brief, then
    # the verbatim tail. Anthropic accepts text-only user messages here, and
    # any tool_use_ids referenced by tool_results in the tail still resolve to
    # the assistant message right before them — which we preserved in the tail.
    brief_message = {
        "role": "user",
        "content": (
            "[Earlier conversation compressed into this brief by the system. "
            "The user's full transcript is preserved separately in the UI.]\n\n"
            + summary_text.strip()
        ),
    }
    compacted = [brief_message, *tail]
    after = estimate_tokens(compacted)
    return compacted, {
        "tokens_before": before,
        "tokens_after": after,
        "summarised_messages": len(head),
        "kept_messages": len(tail),
        "summary_chars": len(summary_text),
        "model": model,
    }
